public struct Permissions: OptionSet, Codable {
    public let rawValue: Int
    public init(rawValue: Int) { self.rawValue = rawValue }
    public static let createInstantInvite = Permissions(rawValue: 0x1)
    public static let kickMembers = Permissions(rawValue: 0x2)
    public static let banMembers = Permissions(rawValue: 0x4)
    public static let administrator = Permissions(rawValue: 0x8)
    public static let manageChannels = Permissions(rawValue: 0x10)
    public static let manageGuild = Permissions(rawValue: 0x20)
    public static let readMessages = Permissions(rawValue: 0x400)
    public static let sendMessages = Permissions(rawValue: 0x800)
    public static let sendTtsMessages = Permissions(rawValue: 0x1000)
    public static let manageMessages = Permissions(rawValue: 0x2000)
    public static let embedLinks = Permissions(rawValue: 0x4000)
    public static let attachFiles = Permissions(rawValue: 0x8000)
    public static let readMessageHistory = Permissions(rawValue: 0x10000)
    public static let mentionEveryone = Permissions(rawValue: 0x20000)
    public static let useExternalEmoji = Permissions(rawValue: 0x40000)
    public static let connect = Permissions(rawValue: 0x100000)
    public static let speak = Permissions(rawValue: 0x200000)
    public static let muteMembers = Permissions(rawValue: 0x400000)
    public static let deafenMembers = Permissions(rawValue: 0x800000)
    public static let moveMembers = Permissions(rawValue: 0x1000000)
    public static let useVoiceActivity = Permissions(rawValue: 0x2000000)
    public static let changeNickname = Permissions(rawValue: 0x4000000)
    public static let manageNicknames = Permissions(rawValue: 0x8000000)
    public static let manageRoles = Permissions(rawValue: 0x10000000)
    public static let manageWebhooks = Permissions(rawValue: 0x20000000)
    public static let manageEmoji = Permissions(rawValue: 0x40000000)
    public static let viewAuditlog = Permissions(rawValue: 0x80)
    public static let addReactions = Permissions(rawValue: 0x40)
}
